services:

  godpostgresdb:
    image: postgres
    shm_size: 256mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: arya
      POSTGRES_DB: librarymanagement

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - godpostgresdb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - godpostgresdb
    volumes:
      - ./uploads:/var/www/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://godpostgresdb:5432/librarymanagement
      SPRING_DATASOURCE_USERNAME: arya
      SPRING_DATASOURCE_PASSWORD: password # I did this on purpose :) nice job


volumes:
  pgdata:
